[package]
name = "sg-com"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", path = "bevy" }
cpal = "0.15.3"
hound = "3.5.1"

[build-dependencies]
bindgen = "0.71.1"
copy_to_output = "2.1.0"
